spring:
  profiles:
    active: ${APP-PROFILE:dev}

  datasource:
    url: jdbc:${MYSQL_URL:mysql://localhost:3306/sales_system}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

cors:
  origin: ${CORS-ORIGINS:http://localhost:4200}

api:
  security:
    token:
      secret: ${SECRET-KEY:development-secret-key}