#spring.datasource.url=jdbc:mysql://localhost:3306/sales_system
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.hibernate.ddl-auto=update
#
#api.security.token.secret=my-secret-key

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sales_system
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 856857708464-1grc5v5gdkihf9456civu19pribp8q0p.apps.googleusercontent.com
            clientSecret: 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

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: my-secret-key
