spring:
  datasource:
    url: "${{MYSQL_URL}}"
    username: "${{MYSQLUSER}}"
    password: "${{MYSQLPASSWORD}}"
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

api:
  security:
    token:
      secret: "${{SECRET-KEY}}"
